### ISSUE TITLE
invalid parametrs from Tonkeeper

### ISSUE THREAD

**Issue by moradpoor** [XaBbl4/pytonconnect#18]
hello , Tonkeeper doesn't accept generated url for connect wallet anymore and show "invalid Parameters" error 
can you please check that ? or guide me for how can I resolve that

**Comment by Laurensavage** [comment]
> hello , Tonkeeper doesn't accept generated url for connect wallet anymore and show "invalid Parameters" error can you please check that ? or guide me for how can I resolve that



Hello @moradpoor 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID TON12938
Please see the link below to our dedicated support line:
[Tonkeeper Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
