### ISSUE TITLE
Is it possible to get message hash after sending the transaction?

### ISSUE THREAD

**Issue by alan890104** [XaBbl4/pytonconnect#3]
I want to get message hash after `connector.send_transaction`,  as `TON CENTER` does.

## Discussion
https://t.me/tondev_eng/44207

**Comment by XaBbl4** [comment]
Try get hash from received boc after send_transaction:
`Cell.one_from_boc(result['boc']).hash.hex()` and use api `toncenter.com/api/v3/transactionsByMessage`

**Comment by alan890104** [comment]
Thank you for your explanation! I will close this issue.
