### ISSUE TITLE
Transaction example improvement

### ISSUE THREAD

**Issue by asemenov-pixelplex** [XaBbl4/pytonconnect#7]
# Description
There is currently no example demonstrating how to deserialize the Bag of Cells (BoC) returned from an executed transaction. Additionally, I find the simple example unclear in certain areas, particularly regarding wallet connection. Moreover, there is a bug that causes the app to crash when running due to the `getConnection` method in the `BridgeProviderStorage` class and failing `send` method of the `BridgeGateway` class.

# Possible solution
Add a new example file that sends a transaction, deserializes the result and shows how to get transaction info.

**Comment by XaBbl4** [comment]
Thanks for contribute.

I fixed this bug in myself, but not pushed yet, because this version is not public to pypi.
There are a few bugs fixed, I’ll try to push them in the next few days if someone is already using this version from github.
